/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-moon-9916fcec59f04b07b3e8d7f077dc3ded
Title: The Moon
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Group, Mesh, Material } from "three";

interface GLTFResult {
  nodes: {
    defaultMaterial: Mesh;
  };
  materials: {
    Material__50: Material;
  };
}

const MODEL_PATH = "src/components/moon/scene.gltf";

export default function Model() {
  const groupRef = useRef<Group>(null);

  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as GLTFResult;

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.x += 0.0005;
      groupRef.current.rotation.y += 0.0005;
      groupRef.current.rotation.z += 0.0005;
    }
  });

  return (
    <group ref={groupRef} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Material__50}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.5}
        />
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_PATH);
